apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-dm
  namespace: fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      name: fs-pod
      labels:
        app: fs
    spec:
      containers:
        - name: fs
          image: /fs/fs:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./fs", "-c", "/app/configs/fs.yml"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: fs-vl
              mountPath: /app/configs/
              readOnly: true
            - name: host-timezone
              mountPath: /etc/localtime
              readOnly: true
          #env:
          #  - name: TZ
          #    value: "Asia/Shanghai"
          
          ports:
            - name: http-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-port
              path: /health

            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo for private repositories, you need to create a secret (here docker-auth-secret) to store the account and password to log into docker
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: fs-vl
          configMap:
            name: fs-config
        - name: host-timezone
          hostPath:
            path: /etc/localtime
            type: File
