version: "3.7"

services:
  fs:
    image: fs/fs:latest
    container_name: fs
    restart: always
    command: ["./fs", "-c", "/app/configs/fs.yml"]
    volumes:
      - $PWD/configs:/app/configs
      - /etc/localtime:/etc/localtime:ro  # mount the local time file
    #environment:
    #  - TZ=Asia/Shanghai
    ports:
      - "8080:8080"   # http port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]   # http health check, note: mirror must contain curl command

      interval: 10s         # interval time
      timeout: 5s           # timeout time
      retries: 3              # number of retries
      start_period: 10s  # how long after start-up does the check begin
